<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.smant</groupId>
    <artifactId>smant-hub</artifactId>
    <version>2024.07.01-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>23</maven.compiler.source>
        <maven.compiler.target>23</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <org.springframework.boot.maven.plugin.version>2.3.0.RELEASE</org.springframework.boot.maven.plugin.version>
        <org.springframework.cloud.dependencies.version>2024.0.0</org.springframework.cloud.dependencies.version>
        <org.springframework.boot.dependencies.version>3.4.0</org.springframework.boot.dependencies.version>
        <com.alibaba.spring.cloud.dependencies.version>2021.0.4.0</com.alibaba.spring.cloud.dependencies.version>
        <com.alibaba.nacos.version>2.4.3</com.alibaba.nacos.version>

        <org.springframework.boot.data.redis.version>3.4.0</org.springframework.boot.data.redis.version>
        <com.alibaba.fastjson2.version>2.0.53</com.alibaba.fastjson2.version>

        <redis.clients.jedis.version>5.2.0</redis.clients.jedis.version>
        <io.lettuce.lettuce-vore.version>6.5.1.RELEASE</io.lettuce.lettuce-vore.version>
        <com.google.guava.version>33.3.1-jre</com.google.guava.version>
        <org.projectlombok.lombok.version>1.18.36</org.projectlombok.lombok.version>
        <mysql.connector.java.version>9.1.0</mysql.connector.java.version>
        <org.mybatis.spring.boot.version>3.0.4</org.mybatis.spring.boot.version>
        <com.baomidou.mybatis-plus.starter.version>3.5.9</com.baomidou.mybatis-plus.starter.version>
        <com.baomidou.dynamic-datasource.boot3.starter.version>4.3.1</com.baomidou.dynamic-datasource.boot3.starter.version>
        <com.alibab.druid.spring-boot3.starter.version>1.2.24</com.alibab.druid.spring-boot3.starter.version>
        <javax.servlet.servlet-api.version>4.0.1</javax.servlet.servlet-api.version>
        <org.mybatis.mybatis-spring.version>3.0.4</org.mybatis.mybatis-spring.version>
        <org.mybatis.mybatis.version>3.5.17</org.mybatis.mybatis.version>
        <com.alibaba.druid.version>1.2.24</com.alibaba.druid.version>

        <!-- plugin version -->
        <org.apache.maven.compiler.plugin.version>3.13.0</org.apache.maven.compiler.plugin.version>
        <org.apache.maven.jar.plugin.version>3.3.0</org.apache.maven.jar.plugin.version>
        <org.apache.maven.site.plugin.version>3.12.1</org.apache.maven.site.plugin.version>
        <org.apache.maven.source.plugin.version>3.2.1</org.apache.maven.source.plugin.version>
        <org.apache.maven.resources.plugin.version>3.3.1</org.apache.maven.resources.plugin.version>
        <org.apache.maven.dependency.plugin.version>2.8</org.apache.maven.dependency.plugin.version>
        <maven.deploy.release.repository.url>http://192.168.22.221:8081/repository/ryds-maven-release/
        </maven.deploy.release.repository.url>
        <maven.deploy.snapshot.repository.url>http://192.168.22.221:8081/repository/ryds-maven-snapshots/
        </maven.deploy.snapshot.repository.url>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${org.springframework.cloud.dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${org.springframework.boot.dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${com.alibaba.spring.cloud.dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>${com.alibaba.nacos.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${com.google.guava.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${org.projectlombok.lombok.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-redis</artifactId>
                <version>${org.springframework.boot.data.redis.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${com.alibaba.fastjson2.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2-extension</artifactId>
                <version>${com.alibaba.fastjson2.version}</version>
            </dependency>
            <dependency>
                <groupId>redis.clients</groupId>
                <artifactId>jedis</artifactId>
                <version>${redis.clients.jedis.version}</version>
            </dependency>
            <dependency>
                <groupId>io.lettuce</groupId>
                <artifactId>lettuce-core</artifactId>
                <version>${io.lettuce.lettuce-vore.version}</version>
            </dependency>
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql.connector.java.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>${org.mybatis.spring.boot.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${com.baomidou.mybatis-plus.starter.version}</version>
            </dependency>

            <!-- mybatis-plus多数据源 -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
                <version>${com.baomidou.dynamic-datasource.boot3.starter.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${com.alibab.druid.spring-boot3.starter.version}</version>
            </dependency>


            <dependency>
                <groupId>javax.servlet</groupId>
                <artifactId>javax.servlet-api</artifactId>
                <version>${javax.servlet.servlet-api.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis-spring</artifactId>
                <version>${org.mybatis.mybatis-spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mybatis</groupId>
                <artifactId>mybatis</artifactId>
                <version>${org.mybatis.mybatis.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid</artifactId>
                <version>${com.alibaba.druid.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>${project.artifactId}</finalName>
        <pluginManagement>
            <plugins>
                <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-maven-plugin -->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${org.springframework.boot.maven.plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${org.apache.maven.compiler.plugin.version}</version>
                    <configuration>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                        <encoding>${project.build.sourceEncoding}</encoding>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${org.apache.maven.resources.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${org.apache.maven.jar.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>${org.apache.maven.site.plugin.version}</version>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>


    <distributionManagement>
        <repository>
            <id>Ryds-Release</id>
            <name>Releases</name>
            <url>${maven.deploy.release.repository.url}</url>
        </repository>
        <snapshotRepository>
            <id>Ryds-Snapshot</id>
            <name>Snapshot</name>
            <url>${maven.deploy.snapshot.repository.url}</url>
        </snapshotRepository>
    </distributionManagement>
</project>
